#!/bin/sh

set -e

SCRIPT_ROOT="`dirname $0`"

if [ "x$VARIANTS" = x ]; then
    VARIANTS=`find "${SCRIPT_ROOT}/conf" -name '*.cfg' -exec basename {} .cfg \; | grep -v common | sort`
fi

cd "${SCRIPT_ROOT}"

if [ "x$1" != x ]; then
    VARIANTS="$1"
fi

for VARIANT in $VARIANTS; do
    make clean

    rm -f app-config
    cp conf/common.cfg app-config
    echo "" >>app-config
    cat conf/${VARIANT}.cfg >>app-config

    BASE_BOARD=`cat app-config | grep "^CONFIG_PLATFORM_" | cut -d '_' -f 3 | cut -d '=' -f 1 | tr -d ' ' | tr 'A-Z' 'a-z'`

    make -j 12
    cp build/${BASE_BOARD}.bin ${BASE_BOARD}-skybrush-${VARIANT}.bin
    rm -f build/*.bin

    # Don't clean up app-config here, the release script needs it
done

